# .github/workflows/esp-idf-build.yml
name: ESP‑IDF Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name:  esp-idf build
        # This action installs the ESP‑IDF tools and sets up the environment.
        target: esp32s3
        uses: espressif/esp-idf-ci-action@v1
        with:
          # You can pin a specific version or use 'latest'
          esp_idf_version:  v5.1.1

      - name: Build the project
        run: |
          # If your project is in a subdirectory, cd into it
          idf.py build
